"""
YT Processing Router
=====================

Provides the AI processing endpoint for the YT Strategy Lab.
Takes raw ingestion data (transcript, metadata, screenshot suggestions)
plus user-provided context and returns a fully populated strategy project
with steps, prompts, and notes — all generated by Claude AI.

Uses the service class pattern — see server/services/yt_processor.py.
"""

import logging
from typing import Optional

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, Field

from ..services.yt_processor import YTProcessor

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/yt-lab", tags=["yt-lab"])


# ---------------------------------------------------------------------------
# Pydantic Schemas
# ---------------------------------------------------------------------------


class TranscriptSegment(BaseModel):
    """A single segment of the video transcript."""

    text: str
    start: float
    duration: float


class ScreenshotSuggestion(BaseModel):
    """A suggested timestamp for capturing a screenshot."""

    timestamp: float
    reason: str
    captured: bool = False
    filepath: Optional[str] = None


class VideoMetadata(BaseModel):
    """Video metadata fields."""

    title: str = "Unknown"
    channel: str = "Unknown"
    duration: int = 0
    description: str = ""


class ProcessRequest(BaseModel):
    """Request body for video processing."""

    video_id: str = Field(..., min_length=1, max_length=64)
    transcript: list[TranscriptSegment]
    metadata: VideoMetadata
    user_context: str = Field("", max_length=10_000)
    extracted_urls: list[str] = []
    screenshot_suggestions: list[ScreenshotSuggestion] = []
    model: str = Field("claude-sonnet-4-6", max_length=100)


class ProjectData(BaseModel):
    """AI-generated project metadata."""

    name: str
    niche: str = ""
    description: str = ""
    tags: list[str] = []


class StepData(BaseModel):
    """AI-generated step data."""

    order: int
    title: str
    description: str = ""
    prompt: str = ""
    expectedOutput: str = ""
    notes: str = ""
    model: str = "claude-sonnet-4-6"


class ProcessResponse(BaseModel):
    """Response from the processing endpoint."""

    project: ProjectData
    steps: list[StepData]
    processing_time: float


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------


@router.post("/process", response_model=ProcessResponse)
async def process_video(body: ProcessRequest):
    """
    Process a YouTube video's transcript and metadata through AI to generate
    a fully populated strategy project with steps, prompts, and notes.

    Requires the anthropic Python package and a valid ANTHROPIC_API_KEY.
    """
    if not body.transcript:
        raise HTTPException(
            status_code=400,
            detail="Transcript is empty — cannot process a video without transcript data.",
        )

    processor = YTProcessor()

    try:
        result = await processor.process(
            video_id=body.video_id,
            transcript=[seg.model_dump() for seg in body.transcript],
            metadata=body.metadata.model_dump(),
            user_context=body.user_context,
            extracted_urls=body.extracted_urls,
            screenshot_suggestions=[s.model_dump() for s in body.screenshot_suggestions],
            model=body.model,
        )
    except RuntimeError as exc:
        # Missing anthropic package or similar setup issue
        logger.error("Processing setup error: %s", exc)
        raise HTTPException(status_code=503, detail=str(exc))
    except ValueError as exc:
        # AI response parsing failure
        logger.error("Processing parse error: %s", exc)
        raise HTTPException(status_code=422, detail=str(exc))
    except Exception as exc:
        logger.exception("Unexpected error during video processing")
        raise HTTPException(status_code=500, detail=f"Processing failed: {exc}")

    return ProcessResponse(
        project=ProjectData(**result["project"]),
        steps=[StepData(**s) for s in result["steps"]],
        processing_time=result["processing_time"],
    )
