"""
YT Processing Router
=====================

Provides the AI processing endpoint for the YT Strategy Lab.
Takes raw ingestion data (transcript, metadata, screenshot suggestions)
plus user-provided context and returns a fully populated strategy project
with steps, prompts, and notes — all generated by Claude AI.

Uses the service class pattern — see server/services/yt_processor.py.
"""

import asyncio
import json
import logging
import time
from typing import Optional

from fastapi import APIRouter, HTTPException
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, Field

from ..services.yt_discovery import YTDiscovery
from ..services.yt_processor import YTProcessor

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/yt-lab", tags=["yt-lab"])


# ---------------------------------------------------------------------------
# Pydantic Schemas
# ---------------------------------------------------------------------------


class TranscriptSegment(BaseModel):
    """A single segment of the video transcript."""

    text: str
    start: float
    duration: float


class ScreenshotSuggestion(BaseModel):
    """A suggested timestamp for capturing a screenshot."""

    timestamp: float
    reason: str
    captured: bool = False
    filepath: Optional[str] = None


class VideoMetadata(BaseModel):
    """Video metadata fields."""

    title: str = "Unknown"
    channel: str = "Unknown"
    duration: int = 0
    description: str = ""


class ProcessRequest(BaseModel):
    """Request body for video processing."""

    video_id: str = Field(..., min_length=1, max_length=64)
    transcript: list[TranscriptSegment]
    metadata: VideoMetadata
    user_context: str = Field("", max_length=10_000)
    extracted_urls: list[str] = []
    screenshot_suggestions: list[ScreenshotSuggestion] = []
    model: str = Field("claude-sonnet-4-6", max_length=100)


class ProjectData(BaseModel):
    """AI-generated project metadata."""

    name: str
    niche: str = ""
    description: str = ""
    tags: list[str] = []


class StepData(BaseModel):
    """AI-generated step data."""

    order: int
    title: str
    description: str = ""
    prompt: str = ""
    expectedOutput: str = ""
    notes: str = ""
    model: str = "claude-sonnet-4-6"


class ProcessResponse(BaseModel):
    """Response from the processing endpoint."""

    project: ProjectData
    steps: list[StepData]
    processing_time: float


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------


@router.post("/process", response_model=ProcessResponse)
async def process_video(body: ProcessRequest):
    """
    Process a YouTube video's transcript and metadata through AI to generate
    a fully populated strategy project with steps, prompts, and notes.

    Requires the anthropic Python package and a valid ANTHROPIC_API_KEY.
    """
    if not body.transcript:
        raise HTTPException(
            status_code=400,
            detail="Transcript is empty — cannot process a video without transcript data.",
        )

    processor = YTProcessor()

    try:
        result = await processor.process(
            video_id=body.video_id,
            transcript=[seg.model_dump() for seg in body.transcript],
            metadata=body.metadata.model_dump(),
            user_context=body.user_context,
            extracted_urls=body.extracted_urls,
            screenshot_suggestions=[s.model_dump() for s in body.screenshot_suggestions],
            model=body.model,
        )
    except RuntimeError as exc:
        # Missing anthropic package or similar setup issue
        logger.error("Processing setup error: %s", exc)
        raise HTTPException(status_code=503, detail=str(exc))
    except ValueError as exc:
        # AI response parsing failure
        logger.error("Processing parse error: %s", exc)
        raise HTTPException(status_code=422, detail=str(exc))
    except Exception as exc:
        logger.exception("Unexpected error during video processing")
        raise HTTPException(status_code=500, detail=f"Processing failed: {exc}")

    return ProcessResponse(
        project=ProjectData(**result["project"]),
        steps=[StepData(**s) for s in result["steps"]],
        processing_time=result["processing_time"],
    )


# ---------------------------------------------------------------------------
# Streaming (SSE) Endpoints — real-time processing logs
# ---------------------------------------------------------------------------


@router.post("/process-stream")
async def process_video_stream(body: ProcessRequest):
    """SSE endpoint that streams real-time progress logs during video processing."""
    if not body.transcript:
        raise HTTPException(
            status_code=400,
            detail="Transcript is empty — cannot process a video without transcript data.",
        )

    queue: asyncio.Queue = asyncio.Queue()
    start_time = time.time()

    def on_progress(message: str) -> None:
        elapsed = round(time.time() - start_time, 1)
        queue.put_nowait({"type": "log", "message": message, "elapsed": elapsed})

    async def run_processing() -> None:
        processor = YTProcessor()
        try:
            result = await processor.process(
                video_id=body.video_id,
                transcript=[seg.model_dump() for seg in body.transcript],
                metadata=body.metadata.model_dump(),
                user_context=body.user_context,
                extracted_urls=body.extracted_urls,
                screenshot_suggestions=[s.model_dump() for s in body.screenshot_suggestions],
                model=body.model,
                on_progress=on_progress,
            )
            elapsed = round(time.time() - start_time, 1)
            queue.put_nowait({"type": "result", "data": result, "elapsed": elapsed})
        except Exception as exc:
            elapsed = round(time.time() - start_time, 1)
            queue.put_nowait({"type": "error", "message": str(exc), "elapsed": elapsed})
        finally:
            queue.put_nowait(None)  # sentinel to end the stream

    # Start processing as a background task
    asyncio.create_task(run_processing())

    async def event_generator():
        while True:
            item = await queue.get()
            if item is None:
                break
            yield f"data: {json.dumps(item)}\n\n"

    return StreamingResponse(event_generator(), media_type="text/event-stream")


@router.post("/discover-stream")
async def discover_opportunities_stream(body: ProcessRequest):
    """SSE endpoint that streams real-time progress logs during opportunity discovery."""
    if not body.transcript:
        raise HTTPException(
            status_code=400,
            detail="Transcript is empty — cannot discover opportunities without transcript data.",
        )

    queue: asyncio.Queue = asyncio.Queue()
    start_time = time.time()

    def on_progress(message: str) -> None:
        elapsed = round(time.time() - start_time, 1)
        queue.put_nowait({"type": "log", "message": message, "elapsed": elapsed})

    async def run_discovery() -> None:
        discovery = YTDiscovery()
        try:
            result = await discovery.discover(
                video_id=body.video_id,
                transcript=[seg.model_dump() for seg in body.transcript],
                metadata=body.metadata.model_dump(),
                user_context=body.user_context,
                extracted_urls=body.extracted_urls,
                screenshot_suggestions=[s.model_dump() for s in body.screenshot_suggestions],
                model=body.model,
                on_progress=on_progress,
            )
            elapsed = round(time.time() - start_time, 1)
            queue.put_nowait({"type": "result", "data": result, "elapsed": elapsed})
        except Exception as exc:
            elapsed = round(time.time() - start_time, 1)
            queue.put_nowait({"type": "error", "message": str(exc), "elapsed": elapsed})
        finally:
            queue.put_nowait(None)  # sentinel to end the stream

    asyncio.create_task(run_discovery())

    async def event_generator():
        while True:
            item = await queue.get()
            if item is None:
                break
            yield f"data: {json.dumps(item)}\n\n"

    return StreamingResponse(event_generator(), media_type="text/event-stream")


# ---------------------------------------------------------------------------
# Discovery Schemas
# ---------------------------------------------------------------------------


class VideoContext(BaseModel):
    """Who is speaking, what the video is about, who benefits."""

    speaker: str = ""
    core_topic: str = ""
    target_audience: str = ""


class KeyInsight(BaseModel):
    """A key lesson or principle from the video."""

    insight: str
    quote: str = ""
    timestamp_approx: str = ""
    applicability: str = ""


class AppOpportunity(BaseModel):
    """A concrete app opportunity identified from the video content."""

    name: str
    type: str = "companion"  # companion | direct | derivative | teaching
    one_liner: str = ""
    description: str = ""
    why_this_works: str = ""
    concerns: str = ""
    complexity: int = Field(3, ge=1, le=5)
    strategic_value: str = ""
    market_signal: str = ""
    features: list[str] = []
    growth_path: str = ""
    score: int = Field(50, ge=0, le=100)


class Recommendation(BaseModel):
    """The AI's recommended path forward."""

    top_pick_index: int = 0
    reasoning: str = ""
    sequence: str = ""
    quick_win: str = ""


class DiscoverResponse(BaseModel):
    """Response from the discovery endpoint."""

    video_context: VideoContext
    key_insights: list[KeyInsight]
    app_opportunities: list[AppOpportunity]
    recommendation: Recommendation
    discovery_time: float


# ---------------------------------------------------------------------------
# Discovery Endpoint
# ---------------------------------------------------------------------------


@router.post("/discover", response_model=DiscoverResponse)
async def discover_opportunities(body: ProcessRequest):
    """
    Analyze a YouTube video's transcript to discover and evaluate app
    opportunities BEFORE building anything.

    Returns key insights, ranked app opportunities with honest evaluation,
    and a recommendation for what to build first.

    Uses the same request schema as /process for consistency.
    """
    if not body.transcript:
        raise HTTPException(
            status_code=400,
            detail="Transcript is empty — cannot discover opportunities without transcript data.",
        )

    discovery = YTDiscovery()

    try:
        result = await discovery.discover(
            video_id=body.video_id,
            transcript=[seg.model_dump() for seg in body.transcript],
            metadata=body.metadata.model_dump(),
            user_context=body.user_context,
            extracted_urls=body.extracted_urls,
            screenshot_suggestions=[s.model_dump() for s in body.screenshot_suggestions],
            model=body.model,
        )
    except RuntimeError as exc:
        logger.error("Discovery setup error: %s", exc)
        raise HTTPException(status_code=503, detail=str(exc))
    except ValueError as exc:
        logger.error("Discovery parse error: %s", exc)
        raise HTTPException(status_code=422, detail=str(exc))
    except Exception as exc:
        logger.exception("Unexpected error during video discovery")
        raise HTTPException(status_code=500, detail=f"Discovery failed: {exc}")

    return DiscoverResponse(
        video_context=VideoContext(**result["video_context"]),
        key_insights=[KeyInsight(**i) for i in result["key_insights"]],
        app_opportunities=[AppOpportunity(**o) for o in result["app_opportunities"]],
        recommendation=Recommendation(**result["recommendation"]),
        discovery_time=result["discovery_time"],
    )
