/**
 * Style definitions for 12 design styles used in AutoForge preview generation.
 * Each style provides a complete set of CSS custom property values that the
 * preview-template.html consumes to render themed UI pages.
 */
export const STYLES = {
  "flat-design": {
    name: "Flat Design",
    vars: {
      "--brand": "#3B82F6",
      "--brand-light": "#60A5FA",
      "--brand-dark": "#2563EB",
      "--surface-canvas": "#FFFFFF",
      "--surface-base": "#F8FAFC",
      "--surface-muted": "#F1F5F9",
      "--text-primary": "#0F172A",
      "--text-secondary": "#475569",
      "--text-tertiary": "#94A3B8",
      "--border": "#CBD5E1",
      "--success": "#22C55E",
      "--error": "#EF4444",
      "--warning": "#F59E0B",
      "--info": "#3B82F6",
      "--font-family": "Inter, system-ui, sans-serif",
      "--card-radius": "8px",
      "--card-shadow": "none",
      "--card-border": "1px solid #E2E8F0",
      "--button-radius": "6px",
    },
  },
  minimalism: {
    name: "Minimalism",
    vars: {
      "--brand": "#111827",
      "--brand-light": "#E5E7EB",
      "--brand-dark": "#030712",
      "--surface-canvas": "#FFFFFF",
      "--surface-base": "#FFFFFF",
      "--surface-muted": "#F9FAFB",
      "--text-primary": "#111827",
      "--text-secondary": "#6B7280",
      "--text-tertiary": "#9CA3AF",
      "--border": "#E5E7EB",
      "--success": "#10B981",
      "--error": "#EF4444",
      "--warning": "#F59E0B",
      "--info": "#6366F1",
      "--font-family": "Inter, system-ui, sans-serif",
      "--card-radius": "12px",
      "--card-shadow": "0 1px 3px rgba(0,0,0,0.04)",
      "--card-border": "1px solid #F3F4F6",
      "--button-radius": "10px",
    },
  },
  neumorphism: {
    name: "Neumorphism",
    vars: {
      "--brand": "#6366F1",
      "--brand-light": "#818CF8",
      "--brand-dark": "#4F46E5",
      "--surface-canvas": "#E0E5EC",
      "--surface-base": "#E0E5EC",
      "--surface-muted": "#D1D9E6",
      "--text-primary": "#2D3748",
      "--text-secondary": "#5A6578",
      "--text-tertiary": "#8A95A5",
      "--border": "transparent",
      "--success": "#48BB78",
      "--error": "#F56565",
      "--warning": "#ECC94B",
      "--info": "#63B3ED",
      "--font-family": "Inter, system-ui, sans-serif",
      "--card-radius": "16px",
      "--card-shadow":
        "8px 8px 16px #b8bec7, -8px -8px 16px #ffffff",
      "--card-border": "none",
      "--button-radius": "12px",
    },
  },
  glassmorphism: {
    name: "Glassmorphism",
    vars: {
      "--brand": "#A855F7",
      "--brand-light": "#C084FC",
      "--brand-dark": "#7C3AED",
      "--surface-canvas": "#667eea",
      "--surface-base": "rgba(255, 255, 255, 0.15)",
      "--surface-muted": "rgba(255, 255, 255, 0.08)",
      "--text-primary": "#FFFFFF",
      "--text-secondary": "rgba(255,255,255,0.8)",
      "--text-tertiary": "rgba(255,255,255,0.5)",
      "--border": "rgba(255,255,255,0.25)",
      "--success": "#4ADE80",
      "--error": "#FB7185",
      "--warning": "#FBBF24",
      "--info": "#60A5FA",
      "--font-family": "Inter, system-ui, sans-serif",
      "--card-radius": "16px",
      "--card-shadow": "0 8px 32px rgba(0,0,0,0.12)",
      "--card-border": "1px solid rgba(255,255,255,0.18)",
      "--button-radius": "12px",
      "--canvas-gradient":
        "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
      "--glass-blur": "16px",
    },
  },
  skeuomorphism: {
    name: "Skeuomorphism",
    vars: {
      "--brand": "#2563EB",
      "--brand-light": "#60A5FA",
      "--brand-dark": "#1D4ED8",
      "--surface-canvas": "#E8E0D8",
      "--surface-base": "#F5F0EB",
      "--surface-muted": "#E0D8CF",
      "--text-primary": "#1A1A1A",
      "--text-secondary": "#4A4A4A",
      "--text-tertiary": "#8A8A8A",
      "--border": "#A89888",
      "--success": "#22A559",
      "--error": "#DC3545",
      "--warning": "#FFC107",
      "--info": "#0D6EFD",
      "--font-family": "Georgia, Palatino, serif",
      "--card-radius": "8px",
      "--card-shadow":
        "0 2px 8px rgba(0,0,0,0.15), inset 0 1px 0 rgba(255,255,255,0.5)",
      "--card-border": "1px solid #C4B8AB",
      "--button-radius": "6px",
    },
  },
  neubrutalism: {
    name: "Neubrutalism",
    vars: {
      "--brand": "#FACC15",
      "--brand-light": "#FDE68A",
      "--brand-dark": "#EAB308",
      "--surface-canvas": "#FFFBEB",
      "--surface-base": "#FFFFFF",
      "--surface-muted": "#FEF3C7",
      "--text-primary": "#18181B",
      "--text-secondary": "#3F3F46",
      "--text-tertiary": "#71717A",
      "--border": "#18181B",
      "--success": "#22C55E",
      "--error": "#EF4444",
      "--warning": "#F97316",
      "--info": "#3B82F6",
      "--font-family": "'Space Grotesk', sans-serif",
      "--card-radius": "0px",
      "--card-shadow": "6px 6px 0px #18181B",
      "--card-border": "3px solid #18181B",
      "--button-radius": "0px",
    },
  },
  bauhaus: {
    name: "Bauhaus",
    vars: {
      "--brand": "#DC2626",
      "--brand-light": "#FCA5A5",
      "--brand-dark": "#991B1B",
      "--surface-canvas": "#FAFAFA",
      "--surface-base": "#FFFFFF",
      "--surface-muted": "#F5F5F5",
      "--text-primary": "#0A0A0A",
      "--text-secondary": "#404040",
      "--text-tertiary": "#737373",
      "--border": "#0A0A0A",
      "--success": "#22C55E",
      "--error": "#DC2626",
      "--warning": "#FACC15",
      "--info": "#2563EB",
      "--font-family": "'DM Sans', 'Helvetica Neue', sans-serif",
      "--card-radius": "0px",
      "--card-shadow": "none",
      "--card-border": "2px solid #0A0A0A",
      "--button-radius": "0px",
    },
  },
  claymorphism: {
    name: "Claymorphism",
    vars: {
      "--brand": "#F59E0B",
      "--brand-light": "#FDE68A",
      "--brand-dark": "#D97706",
      "--surface-canvas": "#FFF7ED",
      "--surface-base": "#FFFFFF",
      "--surface-muted": "#FEF3E2",
      "--text-primary": "#292524",
      "--text-secondary": "#57534E",
      "--text-tertiary": "#A8A29E",
      "--border": "rgba(0,0,0,0.08)",
      "--success": "#4ADE80",
      "--error": "#FB7185",
      "--warning": "#FBBF24",
      "--info": "#60A5FA",
      "--font-family": "Nunito, Quicksand, sans-serif",
      "--card-radius": "24px",
      "--card-shadow":
        "0 8px 30px rgba(0,0,0,0.06), inset 0 -4px 8px rgba(0,0,0,0.04), inset 0 4px 8px rgba(255,255,255,0.8)",
      "--card-border": "none",
      "--button-radius": "20px",
    },
  },
  "retro-futurism": {
    name: "Retro Futurism",
    vars: {
      "--brand": "#D946EF",
      "--brand-light": "#F0ABFC",
      "--brand-dark": "#A21CAF",
      "--surface-canvas": "#0C0A1A",
      "--surface-base": "#1A1730",
      "--surface-muted": "#252040",
      "--text-primary": "#F5F3FF",
      "--text-secondary": "#C4B5FD",
      "--text-tertiary": "#7C3AED",
      "--border": "rgba(217,70,239,0.4)",
      "--success": "#4ADE80",
      "--error": "#FB7185",
      "--warning": "#FBBF24",
      "--info": "#06B6D4",
      "--font-family": "Orbitron, monospace",
      "--card-radius": "8px",
      "--card-shadow":
        "0 0 20px rgba(217,70,239,0.15), inset 0 1px 0 rgba(255,255,255,0.05)",
      "--card-border": "1px solid rgba(217,70,239,0.3)",
      "--button-radius": "4px",
    },
  },
  cyberpunk: {
    name: "Cyberpunk",
    vars: {
      "--brand": "#06B6D4",
      "--brand-light": "#67E8F9",
      "--brand-dark": "#0891B2",
      "--surface-canvas": "#09090B",
      "--surface-base": "#18181B",
      "--surface-muted": "#27272A",
      "--text-primary": "#FAFAFA",
      "--text-secondary": "#A1A1AA",
      "--text-tertiary": "#52525B",
      "--border": "#3F3F46",
      "--success": "#22D3EE",
      "--error": "#F43F5E",
      "--warning": "#FBBF24",
      "--info": "#06B6D4",
      "--font-family": "'JetBrains Mono', 'Fira Code', monospace",
      "--card-radius": "2px",
      "--card-shadow": "0 0 16px rgba(6,182,212,0.08)",
      "--card-border": "1px solid #3F3F46",
      "--button-radius": "2px",
    },
  },
  "dark-mode": {
    name: "Dark Mode Elegant",
    vars: {
      "--brand": "#3B82F6",
      "--brand-light": "#93C5FD",
      "--brand-dark": "#1D4ED8",
      "--surface-canvas": "#0F172A",
      "--surface-base": "#1E293B",
      "--surface-muted": "#334155",
      "--text-primary": "#F1F5F9",
      "--text-secondary": "#94A3B8",
      "--text-tertiary": "#64748B",
      "--border": "#334155",
      "--success": "#4ADE80",
      "--error": "#FB7185",
      "--warning": "#FBBF24",
      "--info": "#60A5FA",
      "--font-family": "Inter, system-ui, sans-serif",
      "--card-radius": "12px",
      "--card-shadow": "0 4px 16px rgba(0,0,0,0.3)",
      "--card-border": "1px solid #334155",
      "--button-radius": "8px",
    },
  },
  "warmer-shades": {
    name: "Warmer Shades",
    vars: {
      "--brand": "#D97706",
      "--brand-light": "#FDE68A",
      "--brand-dark": "#B45309",
      "--surface-canvas": "#FFFBF5",
      "--surface-base": "#FFF8F0",
      "--surface-muted": "#FEF3E2",
      "--text-primary": "#292524",
      "--text-secondary": "#78716C",
      "--text-tertiary": "#A8A29E",
      "--border": "#E7D5C0",
      "--success": "#65A30D",
      "--error": "#DC2626",
      "--warning": "#D97706",
      "--info": "#2563EB",
      "--font-family": "Lora, Merriweather, serif",
      "--card-radius": "12px",
      "--card-shadow": "0 2px 8px rgba(140,100,60,0.06)",
      "--card-border": "1px solid #F5E6D3",
      "--button-radius": "10px",
    },
  },
};
