#!/usr/bin/env python3
"""
Sweep 3 — Render

Pure Python — no LLM calls. Reads clusters.json + taxonomy.json and writes:
  {output_dir}/truth_document.md   ← master single-file truth doc
  {output_dir}/sections/           ← per-bucket .md files
  {output_dir}/_index.md           ← summary index with counts

One section file per bucket. Clusters sorted largest-first (most recurring
patterns at the top). Singletons appended at the bottom of each section.
"""

import argparse
import json
import sys
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from _claude import load_config


# =============================================================================
# HELPERS
# =============================================================================

def slugify(name: str) -> str:
    import re
    s = name.lower().strip()
    s = re.sub(r"[^a-z0-9\-]", "-", s)
    s = re.sub(r"-+", "-", s).strip("-")
    return s or "misc"


def format_item(item: dict, indent: str = "") -> str:
    verbatim = item.get("verbatim", "").strip()
    source   = item.get("source_folder", "")
    context  = item.get("context_note", "").strip()
    if not verbatim:
        return ""
    lines = [f'{indent}- "{verbatim}"']
    if context:
        lines.append(f"{indent}  *({context})*")
    if source:
        lines.append(f"{indent}  — `{source}`")
    return "\n".join(lines) + "\n"


# =============================================================================
# MAIN SWEEP
# =============================================================================

def run(cfg: dict) -> dict:
    output_dir   = Path(cfg["output_dir"])
    sections_dir = output_dir / "sections"
    sections_dir.mkdir(parents=True, exist_ok=True)

    clusters_path = output_dir / "clusters.json"
    taxonomy_path = output_dir / "taxonomy.json"
    truth_doc_path = output_dir / "truth_document.md"
    index_path     = output_dir / "_index.md"

    if not clusters_path.exists():
        print(f"  ERROR: clusters.json not found: {clusters_path}")
        print("  Run Sweep 2 first.")
        return {}

    clusters_data = json.loads(clusters_path.read_text(encoding="utf-8"))
    taxonomy_data = json.loads(taxonomy_path.read_text(encoding="utf-8")) if taxonomy_path.exists() else {}

    categories   = taxonomy_data.get("categories", [])
    bucket_order = [c["name"] for c in categories]
    bucket_labels = {c["name"]: c["label"] for c in categories}

    # Group clusters by bucket
    by_bucket: dict[str, list[dict]] = defaultdict(list)
    for cluster in clusters_data.get("clusters", []):
        bucket = cluster.get("bucket") or "misc"
        by_bucket[bucket].append(cluster)

    singleton_by_bucket: dict[str, list[dict]] = defaultdict(list)
    for item in clusters_data.get("singletons", []):
        bucket = item.get("bucket") or "misc"
        singleton_by_bucket[bucket].append(item)

    # All buckets in taxonomy order, then any extra found in data
    all_buckets_data = set(by_bucket.keys()) | set(singleton_by_bucket.keys())
    ordered = [b for b in bucket_order if b in all_buckets_data]
    extras  = sorted(all_buckets_data - set(ordered))
    all_buckets = ordered + extras

    project_name   = cfg.get("project_name", "Channel")
    total_items    = clusters_data.get("total_items", "?")
    cluster_count  = clusters_data.get("cluster_count", "?")
    singleton_count = clusters_data.get("singleton_count", "?")

    truth_parts  = [
        f"# {project_name} — Source of Truth\n\n",
        f"> Auto-generated by truth_builder_v2.\n",
        f"> {total_items} total extractions | {cluster_count} clusters | {singleton_count} singletons\n\n",
    ]

    written_sections: list[tuple] = []  # (bucket, label, slug, cluster_count)

    for bucket in all_buckets:
        label    = bucket_labels.get(bucket, bucket.replace("-", " ").title())
        clusters = sorted(by_bucket.get(bucket, []), key=lambda c: c.get("size", 1), reverse=True)
        singletons = singleton_by_bucket.get(bucket, [])

        if not clusters and not singletons:
            continue

        section_parts = [f"# {label}\n\n"]

        for cluster in clusters:
            cluster_label = (cluster.get("label") or "").strip()
            items         = cluster.get("items", [])
            size          = cluster.get("size", len(items))

            if cluster_label and cluster_label not in ("singleton", "batch_failed", "parse_failed"):
                section_parts.append(f"## {cluster_label}  *(×{size})*\n\n")
            elif size > 1:
                rep = (cluster.get("representative") or "")[:80]
                section_parts.append(f"## {rep}...  *(×{size})*\n\n")

            for item in items:
                line = format_item(item)
                if line:
                    section_parts.append(line)
            section_parts.append("\n")

        if singletons:
            section_parts.append("## Unique Instances\n\n")
            for item in singletons:
                line = format_item(item)
                if line:
                    section_parts.append(line)
            section_parts.append("\n")

        section_text = "".join(section_parts)

        # Write per-section file
        slug = slugify(bucket)
        section_path = sections_dir / f"{slug}.md"
        section_path.write_text(section_text, encoding="utf-8")

        written_sections.append((bucket, label, slug, len(clusters) + len(singletons)))

        # Add to master truth doc (replace h1 → h2)
        truth_parts.append(f"## {label}\n\n")
        body = section_text.split("\n", 1)[1].lstrip("\n") if "\n" in section_text else ""
        truth_parts.append(body)
        truth_parts.append("\n---\n\n")

    truth_doc_path.write_text("".join(truth_parts), encoding="utf-8")

    # Write _index.md
    index_lines = [
        f"# {project_name} — Index\n\n",
        f"| Stat | Value |\n|------|-------|\n",
        f"| Total extractions | {total_items} |\n",
        f"| Cluster groups    | {cluster_count} |\n",
        f"| Singletons        | {singleton_count} |\n",
        f"| Sections          | {len(written_sections)} |\n\n",
        "## Sections\n\n",
    ]
    for bucket, label, slug, count in written_sections:
        index_lines.append(f"- [{label}](sections/{slug}.md) — {count} groups\n")
    index_lines.append(f"\n[Full truth doc](truth_document.md)\n")
    index_path.write_text("".join(index_lines), encoding="utf-8")

    print(f"  Sweep 3 done: {len(written_sections)} sections written")
    print(f"  Truth doc:  {truth_doc_path}")
    print(f"  Index:      {index_path}")

    return {
        "truth_doc":  str(truth_doc_path),
        "index":      str(index_path),
        "sections":   len(written_sections),
        "output_dir": str(output_dir),
    }


# =============================================================================
# STANDALONE ENTRY
# =============================================================================

def main() -> None:
    ap = argparse.ArgumentParser(description="Sweep 3: Render to Markdown")
    ap.add_argument("--config", required=True)
    args = ap.parse_args()
    cfg = load_config(args.config)
    run(cfg)


if __name__ == "__main__":
    main()
