"""
Truth Builder Service
=====================

Processes YouTube video transcripts through Claude AI (subscription SDK)
to build a cumulative "source of truth" document about an AI agency
business model.

Reads video folders from a local directory, processes each one through
Claude, and appends new information to a master truth document.

SDK pattern copied exactly from yt_processor.py._call_via_sdk().
"""

import asyncio
import json
import logging
import os
import shutil
import tempfile
import time
import uuid
from datetime import datetime
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Paths (hardcoded per user request)
# ---------------------------------------------------------------------------

VIDEOS_DIR = Path(r"C:\Users\lober\GitHub\Greptacular - AutoForge Build\Greptacular\output\videos")
OUTPUT_DIR = Path(r"C:\Users\lober\GitHub\Greptacular - AutoForge Build\Greptacular\output")
TRUTH_DOC_PATH = OUTPUT_DIR / "truth_document.md"
LOG_PATH = OUTPUT_DIR / "truth_builder_log.txt"

# Model for truth building (Sonnet is fast and cheap on subscription)
TRUTH_BUILDER_MODEL = "claude-sonnet-4-6"

# SDK timeout: 3 minutes per video (transcripts are smaller than full
# strategy extraction payloads)
SDK_TIMEOUT_SECONDS = 180

# ---------------------------------------------------------------------------
# System prompt for truth extraction
# ---------------------------------------------------------------------------

TRUTH_BUILDER_SYSTEM_PROMPT = """You are building a master "source of truth" document about an AI agency business model from YouTube video transcripts.

The document has these sections:
## Services & Pricing
## Free Tools & Assets
## Sales Scripts & Pitches
## Client Acquisition Methods
## Automation & Tech Stack
## Niche Strategy & Target Markets
## Retention & Anti-Churn
## Scaling & Hiring
## Misc Tactics & Nuggets

For each video transcript:
- Extract ONLY information that is NEW vs what's already in the truth doc
- SKIP: promotional filler, book-a-call pitches, repeats
- KEEP: specific numbers, prices, scripts, tool names, URLs, tactics, workflows
- Return raw JSON only (no markdown fences):
{"has_new_info": true/false, "updates": {"Services & Pricing": "text or null", ...}, "video_summary": "1-2 sentences"}"""

# ---------------------------------------------------------------------------
# Truth document template (used when creating a fresh document)
# ---------------------------------------------------------------------------

TRUTH_DOC_TEMPLATE = """# AI Agency Business Model — Source of Truth

> Auto-generated by Truth Builder. Each section is cumulative across all
> processed video transcripts.

## Services & Pricing

## Free Tools & Assets

## Sales Scripts & Pitches

## Client Acquisition Methods

## Automation & Tech Stack

## Niche Strategy & Target Markets

## Retention & Anti-Churn

## Scaling & Hiring

## Misc Tactics & Nuggets
"""

# Section headers in the order they appear in the truth doc
SECTION_HEADERS = [
    "Services & Pricing",
    "Free Tools & Assets",
    "Sales Scripts & Pitches",
    "Client Acquisition Methods",
    "Automation & Tech Stack",
    "Niche Strategy & Target Markets",
    "Retention & Anti-Churn",
    "Scaling & Hiring",
    "Misc Tactics & Nuggets",
]


# ---------------------------------------------------------------------------
# Singleton job state (no database — just in-memory + file-based)
# ---------------------------------------------------------------------------

class _JobState:
    """In-memory state for the currently running (or last completed) job."""

    def __init__(self) -> None:
        self.status: str = "idle"  # idle | running | done | error
        self.job_id: Optional[str] = None
        self.progress: str = ""
        self.last_video: str = ""
        self.error_message: str = ""
        self.started_at: Optional[float] = None
        self.finished_at: Optional[float] = None

    def reset(self, job_id: str) -> None:
        self.status = "running"
        self.job_id = job_id
        self.progress = "0/0 videos"
        self.last_video = ""
        self.error_message = ""
        self.started_at = time.time()
        self.finished_at = None


_state = _JobState()


def get_job_state() -> dict:
    """Return the current job state as a plain dict for the status endpoint."""
    log_tail = _read_log_tail(20)
    return {
        "status": _state.status,
        "job_id": _state.job_id,
        "progress": _state.progress,
        "last_video": _state.last_video,
        "error_message": _state.error_message,
        "log_tail": log_tail,
    }


def get_truth_document() -> str:
    """Return the truth document content, or empty string if it doesn't exist."""
    if TRUTH_DOC_PATH.exists():
        return TRUTH_DOC_PATH.read_text(encoding="utf-8")
    return ""


def is_running() -> bool:
    """Check if a job is currently running."""
    return _state.status == "running"


# ---------------------------------------------------------------------------
# File helpers
# ---------------------------------------------------------------------------

def _read_log_tail(n: int = 20) -> str:
    """Read the last N lines from the log file."""
    if not LOG_PATH.exists():
        return ""
    try:
        lines = LOG_PATH.read_text(encoding="utf-8").strip().splitlines()
        return "\n".join(lines[-n:])
    except Exception:
        return ""


def _append_log(message: str) -> None:
    """Append a timestamped line to the log file."""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    line = f"[{timestamp}] {message}\n"
    try:
        OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
        with open(LOG_PATH, "a", encoding="utf-8") as f:
            f.write(line)
    except Exception as exc:
        logger.error("Failed to write to truth builder log: %s", exc)


def _get_processed_videos() -> set[str]:
    """Read the log file and return the set of already-processed video folder names."""
    if not LOG_PATH.exists():
        return set()
    processed = set()
    try:
        for line in LOG_PATH.read_text(encoding="utf-8").splitlines():
            # Lines that mark successful processing contain "DONE:"
            if "DONE:" in line:
                # Format: [timestamp] DONE: folder_name
                parts = line.split("DONE:", 1)
                if len(parts) == 2:
                    folder_name = parts[1].strip()
                    if folder_name:
                        processed.add(folder_name)
    except Exception:
        pass
    return processed


def _get_video_folders() -> list[Path]:
    """Get video folders sorted by modification time (oldest first).

    Each valid folder must contain a transcript.txt file.
    """
    if not VIDEOS_DIR.exists():
        return []
    folders = []
    for entry in sorted(VIDEOS_DIR.iterdir()):
        if entry.is_dir() and (entry / "transcript.txt").exists():
            folders.append(entry)
    # Sort by modification time (oldest first)
    folders.sort(key=lambda p: p.stat().st_mtime)
    return folders


def _read_truth_doc() -> str:
    """Read the current truth document, creating it from template if missing."""
    if TRUTH_DOC_PATH.exists():
        return TRUTH_DOC_PATH.read_text(encoding="utf-8")
    # Create initial document from template
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    TRUTH_DOC_PATH.write_text(TRUTH_DOC_TEMPLATE, encoding="utf-8")
    return TRUTH_DOC_TEMPLATE


def _save_truth_doc(content: str) -> None:
    """Save the truth document to disk."""
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    TRUTH_DOC_PATH.write_text(content, encoding="utf-8")


def _merge_updates(truth_doc: str, updates: dict) -> str:
    """Merge new section updates into the truth document.

    For each section that has new text, append it under the matching
    ## header in the document.
    """
    for section_name, new_text in updates.items():
        if not new_text or new_text == "null" or str(new_text).strip().lower() == "null":
            continue
        header = f"## {section_name}"
        if header not in truth_doc:
            # Section header missing — append it at the end
            truth_doc += f"\n{header}\n\n{new_text}\n"
        else:
            # Find the header and append after it (before the next ## or end)
            idx = truth_doc.index(header)
            # Find the end of the header line
            header_end = truth_doc.index("\n", idx) if "\n" in truth_doc[idx:] else len(truth_doc)
            # Find the next ## header (or end of document)
            next_header_idx = len(truth_doc)
            for other_header in SECTION_HEADERS:
                marker = f"\n## {other_header}"
                pos = truth_doc.find(marker, header_end)
                if pos >= 0 and pos < next_header_idx:
                    next_header_idx = pos
            # Insert the new text before the next section
            insertion_point = next_header_idx
            new_block = f"\n{new_text.strip()}\n"
            truth_doc = truth_doc[:insertion_point] + new_block + truth_doc[insertion_point:]
    return truth_doc


# ---------------------------------------------------------------------------
# SDK call — copied exactly from yt_processor.py._call_via_sdk()
# ---------------------------------------------------------------------------

async def _call_via_sdk(
    system_prompt: str,
    user_message: str,
    model: str,
    timeout: float | None = None,
) -> str:
    """Call Claude via the Agent SDK using SUBSCRIPTION auth ONLY.

    Uses ``ClaudeSDKClient`` with ``force_subscription=True`` — clears
    API key so the CLI falls back to ``~/.claude/.credentials.json``
    (subscription OAuth).  NO API CREDITS BURNED.

    IMPORTANT: Uses ``permission_mode="acceptEdits"`` to match ALL
    working SDK clients in this codebase.

    AGENTS: DO NOT add an API key fallback here.
    """
    from claude_agent_sdk import ClaudeAgentOptions, ClaudeSDKClient

    from registry import get_effective_sdk_env

    t0 = time.time()

    # CRITICAL: Remove CLAUDECODE env var — it blocks nested Claude CLI sessions.
    os.environ.pop("CLAUDECODE", None)

    system_cli = shutil.which("claude")
    if not system_cli:
        raise RuntimeError("Claude CLI not found on PATH")
    logger.info("[truth-builder SDK] CLI binary: %s", system_cli)

    sdk_env = get_effective_sdk_env(force_subscription=True)
    sdk_env.pop("CLAUDECODE", None)

    # Subscription verification
    api_key_val = sdk_env.get("ANTHROPIC_API_KEY", "(NOT SET)")
    has_api_key = bool(api_key_val and api_key_val not in ("", "(NOT SET)"))
    if has_api_key:
        logger.warning("[truth-builder SDK] API key present despite force_subscription=True!")

    t1 = time.time()
    logger.info("[truth-builder SDK] Auth setup: %.1fs", t1 - t0)

    # Use a temp directory as cwd
    scratch = tempfile.mkdtemp(prefix="truth_builder_")

    # Create settings file matching the working pattern
    import pathlib as _pl
    settings_file = _pl.Path(scratch) / ".claude-truth-settings.json"
    settings_file.write_text(json.dumps({
        "permissions": {
            "defaultMode": "acceptEdits",
            "allow": [],
        },
    }))

    client = ClaudeSDKClient(
        options=ClaudeAgentOptions(
            model=model,
            cli_path=system_cli,
            system_prompt=system_prompt,
            env=sdk_env,
            max_turns=2,
            permission_mode="acceptEdits",
            allowed_tools=[],
            cwd=scratch,
            settings=str(settings_file.resolve()),
            setting_sources=["user"],
        )
    )

    t2 = time.time()
    logger.info(
        "[truth-builder SDK] Client created: %.1fs | model=%s | mode=acceptEdits",
        t2 - t1, model,
    )

    effective_timeout = timeout if timeout is not None else SDK_TIMEOUT_SECONDS
    logger.info(
        "[truth-builder SDK] Timeout: %ss | Payload: %s chars",
        effective_timeout, f"{len(user_message):,}",
    )

    async def _run_sdk() -> str:
        sdk_t0 = time.time()
        logger.info("[truth-builder SDK] Spawning CLI subprocess...")

        try:
            await client.__aenter__()
        except Exception as enter_err:
            err_str = str(enter_err)
            logger.error("[truth-builder SDK] CLI FAILED TO START: %s", err_str)
            raise RuntimeError(
                f"Claude CLI failed to start (model={model}): {err_str}"
            ) from enter_err

        sdk_t1 = time.time()
        logger.info("[truth-builder SDK] CLI subprocess ready: %.1fs", sdk_t1 - sdk_t0)

        logger.info("[truth-builder SDK] Sending query (%s chars)...", f"{len(user_message):,}")
        await client.query(user_message)
        sdk_t2 = time.time()
        logger.info(
            "[truth-builder SDK] Query sent: %.1fs — now waiting for %s to respond...",
            sdk_t2 - sdk_t1, model,
        )

        full_text = ""
        msg_count = 0
        sdk_error: str | None = None
        rate_limit_count = 0

        # The SDK may THROW "Unknown message type: rate_limit_event"
        # instead of yielding it.  If we already have content, catch
        # the exception and use what we collected.
        try:
            async for msg in client.receive_response():
                msg_type = type(msg).__name__
                msg_count += 1

                if msg_type in ("RateLimitEvent", "rate_limit_event"):
                    rate_limit_count += 1
                    logger.warning("[truth-builder SDK] Rate limit #%d", rate_limit_count)
                    continue

                elif msg_type == "AssistantMessage" and hasattr(msg, "content"):
                    for block in msg.content:
                        block_type = type(block).__name__
                        if block_type == "TextBlock" and hasattr(block, "text"):
                            full_text += block.text

                elif msg_type == "ResultMessage":
                    is_error = getattr(msg, "is_error", False)
                    if is_error:
                        result_text = ""
                        if hasattr(msg, "result") and msg.result:
                            result_text = str(msg.result)[:500]
                        elif hasattr(msg, "content"):
                            for block in getattr(msg, "content", []):
                                if hasattr(block, "text"):
                                    result_text += block.text
                        sdk_error = f"SDK error (model={model}): {result_text}" if result_text else f"SDK ResultMessage error (model={model})"
                        logger.error("[truth-builder SDK] ERROR: %s", sdk_error)
                    else:
                        logger.info("[truth-builder SDK] DONE | %s chars total", f"{len(full_text):,}")

        except Exception as stream_exc:
            exc_str = str(stream_exc)
            logger.warning("[truth-builder SDK] Stream exception: %s", exc_str)
            if full_text.strip() and "unknown message type" in exc_str.lower():
                logger.info("[truth-builder SDK] Recovered: using %s chars despite SDK error", f"{len(full_text):,}")
            elif full_text.strip():
                logger.warning("[truth-builder SDK] Stream error after receiving %s chars", f"{len(full_text):,}")
            else:
                raise

        if sdk_error:
            raise RuntimeError(sdk_error)

        if not full_text.strip():
            raise RuntimeError(
                f"Claude SDK returned empty response. "
                f"Messages: {msg_count}, Rate limits: {rate_limit_count}"
            )
        return full_text.strip()

    try:
        return await asyncio.wait_for(_run_sdk(), timeout=effective_timeout)
    except asyncio.TimeoutError:
        elapsed = time.time() - t0
        logger.error("[truth-builder SDK] TIMEOUT after %.0fs (limit: %ss)", elapsed, effective_timeout)
        raise RuntimeError(
            f"Claude SDK timed out after {effective_timeout}s. Try again."
        )
    finally:
        try:
            await client.__aexit__(None, None, None)
        except Exception:
            pass
        try:
            shutil.rmtree(scratch, ignore_errors=True)
        except Exception:
            pass


# ---------------------------------------------------------------------------
# Main pipeline
# ---------------------------------------------------------------------------

async def run_truth_builder(output_dir: Optional[str] = None) -> str:
    """Run the truth builder pipeline as a background task.

    Returns the job_id immediately. The pipeline runs asynchronously
    and updates _state as it progresses.
    """
    if is_running():
        raise RuntimeError("Truth builder is already running")

    job_id = str(uuid.uuid4())[:8]
    _state.reset(job_id)

    # Allow overriding output paths
    truth_doc_path = TRUTH_DOC_PATH
    log_path = LOG_PATH
    if output_dir:
        out = Path(output_dir)
        truth_doc_path = out / "truth_document.md"
        log_path = out / "truth_builder_log.txt"

    # Launch the pipeline as a background task
    asyncio.create_task(_run_pipeline(job_id, truth_doc_path, log_path))
    return job_id


async def _run_pipeline(
    job_id: str,
    truth_doc_path: Path,
    log_path: Path,
) -> None:
    """The actual pipeline loop — runs as an asyncio background task."""
    try:
        _append_log(f"=== Truth Builder started (job {job_id}) ===")

        # Discover video folders
        all_folders = _get_video_folders()
        if not all_folders:
            _state.status = "done"
            _state.progress = "0/0 videos (no video folders found)"
            _append_log("No video folders found. Nothing to process.")
            return

        # Filter out already-processed videos
        processed = _get_processed_videos()
        pending = [f for f in all_folders if f.name not in processed]

        total = len(all_folders)
        already_done = len(processed)
        to_process = len(pending)

        _append_log(f"Found {total} video folders, {already_done} already processed, {to_process} to process")
        _state.progress = f"0/{to_process} videos"

        if to_process == 0:
            _state.status = "done"
            _state.progress = f"{total}/{total} videos (all already processed)"
            _append_log("All videos already processed. Nothing new to do.")
            return

        # Load (or create) the truth document
        truth_doc = _read_truth_doc()

        for i, folder in enumerate(pending, start=1):
            folder_name = folder.name
            _state.progress = f"{i}/{to_process} videos"
            _state.last_video = folder_name
            _append_log(f"Processing [{i}/{to_process}]: {folder_name}")

            try:
                # Read transcript
                transcript_path = folder / "transcript.txt"
                transcript = transcript_path.read_text(encoding="utf-8")

                # Read info.md if it exists
                info_path = folder / "info.md"
                info_text = ""
                if info_path.exists():
                    info_text = info_path.read_text(encoding="utf-8")

                # Build the user message
                user_message = _build_user_message(
                    folder_name=folder_name,
                    transcript=transcript,
                    info_text=info_text,
                    current_truth_doc=truth_doc,
                )

                # Call Claude via subscription SDK
                raw_response = await _call_via_sdk(
                    system_prompt=TRUTH_BUILDER_SYSTEM_PROMPT,
                    user_message=user_message,
                    model=TRUTH_BUILDER_MODEL,
                )

                # Parse the JSON response
                result = _parse_response(raw_response)

                if result.get("has_new_info"):
                    updates = result.get("updates", {})
                    truth_doc = _merge_updates(truth_doc, updates)
                    _save_truth_doc(truth_doc)
                    summary = result.get("video_summary", "")
                    _append_log(f"DONE: {folder_name} | NEW INFO | {summary}")
                else:
                    summary = result.get("video_summary", "")
                    _append_log(f"DONE: {folder_name} | no new info | {summary}")

            except Exception as exc:
                _append_log(f"ERROR: {folder_name} | {exc}")
                logger.exception("Truth builder failed on video: %s", folder_name)
                # Continue with the next video instead of aborting

            # Small delay between videos to avoid rate limiting
            await asyncio.sleep(2)

        _state.status = "done"
        _state.progress = f"{to_process}/{to_process} videos"
        _state.finished_at = time.time()
        elapsed = _state.finished_at - (_state.started_at or _state.finished_at)
        _append_log(f"=== Truth Builder finished (job {job_id}) in {elapsed:.0f}s ===")

    except Exception as exc:
        _state.status = "error"
        _state.error_message = str(exc)
        _append_log(f"FATAL ERROR: {exc}")
        logger.exception("Truth builder pipeline failed")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _build_user_message(
    folder_name: str,
    transcript: str,
    info_text: str,
    current_truth_doc: str,
) -> str:
    """Build the user message for Claude with the video data and current truth doc."""
    parts = []

    parts.append(f"## Video: {folder_name}")

    if info_text:
        parts.append(f"## Video Info\n{info_text}")

    parts.append(f"## Transcript\n{transcript}")

    # Include the current truth doc so Claude knows what's already captured
    parts.append(f"## Current Truth Document\n{current_truth_doc}")

    return "\n\n".join(parts)


def _parse_response(raw_text: str) -> dict:
    """Parse the JSON response from Claude.

    Handles common LLM output issues: markdown fences, preamble text,
    trailing commentary.
    """
    text = raw_text.strip()

    # Try direct parse
    try:
        return json.loads(text)
    except (json.JSONDecodeError, ValueError):
        pass

    # Strip markdown code fences
    import re
    if "```" in text:
        fence_match = re.search(r"```(?:json)?\s*\n?(.*?)```", text, re.DOTALL)
        if fence_match:
            fenced = fence_match.group(1).strip()
            try:
                return json.loads(fenced)
            except (json.JSONDecodeError, ValueError):
                pass

    # Extract first balanced JSON object
    first_brace = text.find("{")
    last_brace = text.rfind("}")
    if first_brace >= 0 and last_brace > first_brace:
        candidate = text[first_brace:last_brace + 1]
        try:
            return json.loads(candidate)
        except (json.JSONDecodeError, ValueError):
            pass

    # If all parsing fails, return a safe fallback
    logger.error("Failed to parse truth builder response. Raw text:\n%s", text[:1000])
    return {"has_new_info": False, "updates": {}, "video_summary": "Parse error — skipped"}
