/**
 * ProductPanel Component
 *
 * Collapsible side panel showing product layer documents.
 * Read-only display (product files are generated by the workflow).
 */

import { useState } from 'react'
import { ChevronDown, ChevronRight, FileText } from 'lucide-react'
import { Card, CardContent } from '@/components/ui/card'
import { useProductFiles, useProductFile } from '@/hooks/useAgentOS'

interface ProductPanelProps {
  projectName: string
  isOpen: boolean
  onToggle: () => void
}

export function ProductPanel({ projectName, isOpen, onToggle }: ProductPanelProps) {
  const { data } = useProductFiles(projectName)
  const files = data?.files ?? []

  if (!isOpen) {
    return (
      <button
        onClick={onToggle}
        className="flex items-center gap-2 px-3 py-2 text-xs font-bold text-foreground hover:bg-muted/50 rounded-lg w-full text-left transition-colors"
      >
        <ChevronRight size={14} />
        <FileText size={14} className="text-purple-500" />
        Product ({files.length})
      </button>
    )
  }

  return (
    <Card>
      <CardContent className="p-0">
        <button
          onClick={onToggle}
          className="flex items-center justify-between w-full px-3 py-2 border-b border-border hover:bg-muted/30 transition-colors"
        >
          <div className="flex items-center gap-2">
            <ChevronDown size={14} />
            <FileText size={14} className="text-purple-500" />
            <span className="text-xs font-bold text-foreground">Product</span>
          </div>
          <span className="text-[10px] text-muted-foreground">{files.length} files</span>
        </button>

        <div className="divide-y divide-border/50">
          {files.length === 0 ? (
            <div className="px-3 py-4 text-center text-xs text-muted-foreground">
              No product documents yet
            </div>
          ) : (
            files.map(file => (
              <ProductFileItem
                key={file.name}
                projectName={projectName}
                filename={file.name}
              />
            ))
          )}
        </div>
      </CardContent>
    </Card>
  )
}

// ============================================================================
// File accordion item (read-only)
// ============================================================================

function ProductFileItem({ projectName, filename }: { projectName: string; filename: string }) {
  const [expanded, setExpanded] = useState(false)
  const { data: fileData } = useProductFile(projectName, expanded ? filename : '')

  const displayName = filename
    .replace(/\.md$/, '')
    .replace(/-/g, ' ')
    .replace(/\b\w/g, c => c.toUpperCase())

  return (
    <div>
      <button
        onClick={() => setExpanded(prev => !prev)}
        className="flex items-center gap-2 w-full px-3 py-2 text-left hover:bg-muted/20 transition-colors"
      >
        {expanded ? <ChevronDown size={12} /> : <ChevronRight size={12} />}
        <span className="text-xs font-medium text-foreground">{displayName}</span>
      </button>

      {expanded && (
        <div className="px-3 pb-3">
          <pre className="text-[11px] text-muted-foreground whitespace-pre-wrap font-mono leading-relaxed max-h-48 overflow-y-auto">
            {fileData?.content || '(loading...)'}
          </pre>
        </div>
      )}
    </div>
  )
}
