#!/usr/bin/env python3
"""
Truth Builder
=============
Reads transcripts from output/videos/ (generated by youtube_analyzer.py),
then calls Claude to process them oldest-first, building a rolling truth document.

For each transcript Claude is asked: "What is NEW here that isn't already in the
truth document?" Only new tactics, tools, workflows, and prices are kept.
Promotions, repetition, and vague motivational content are discarded.

The truth document is saved after every video so you can stop and resume anytime.

Usage:
  Set your Anthropic API key below (or as env var ANTHROPIC_API_KEY), then:
  python tools/truth_builder.py

Requirements:
  pip install anthropic
"""

import os
import time
from pathlib import Path
import anthropic

# ── Config ────────────────────────────────────────────────────────────────────

ANTHROPIC_API_KEY = ""          # paste key here, or set ANTHROPIC_API_KEY env var
OUTPUT_DIR        = Path("output")
TRUTH_DOC_PATH    = OUTPUT_DIR / "truth_document.md"
PROGRESS_PATH     = OUTPUT_DIR / "truth_progress.txt"
MODEL             = "claude-sonnet-4-6"

# ── Prompts ───────────────────────────────────────────────────────────────────

SYSTEM = """\
You are building a distilled knowledge document from YouTube transcripts about running an AI agency.

Your only job is to find information in the new transcript that is NOT already covered in the
current truth document, and add it.

Strict rules:
- Skip anything already in the truth document — even if worded differently
- Skip all promotional content: "book a call", "subscribe", course upsells, affiliate links
- Skip vague motivational filler with no actionable content
- Skip short-form Shorts that are just teasers with no real content
- KEEP: specific tools and their names, prices, workflows, scripts, cold call techniques,
  software configurations, automation steps, templates, free assets, pricing models
- Format additions as bullet points under the correct section heading
- If the section doesn't exist yet in the truth document, create it
- If there is genuinely nothing new, reply with exactly: NO_NEW_INFO
- Do not summarize or restate what's already there — only additions
"""

SECTIONS = """\
## Services & Pricing
## Tools & Software Used
## Free Assets & Templates
## Client Acquisition (Cold Calling / Outreach)
## Automations & Workflows
## GoHighLevel Specifics
## AI Voice Agents
## AI Website Builder
## Lead Generation
## Mindset / Business Lessons
"""

INITIAL_DOC = f"""# Connor Cahill — Distilled Knowledge Base

*Built by truth_builder.py — only new, actionable information is added.*
*Oldest videos processed first. Duplicates and promotions are stripped.*

---

{SECTIONS}"""

# ── Helpers ───────────────────────────────────────────────────────────────────

def get_video_folders():
    """Return video folders sorted oldest-first."""
    vdir = OUTPUT_DIR / "videos"
    if not vdir.exists():
        print("ERROR: output/videos/ not found. Run youtube_analyzer.py first.")
        return []
    return sorted(vdir.iterdir())  # YYYY-MM-DD prefix = chronological sort


def read_transcript(folder):
    """Return transcript text, or None if unavailable."""
    path = folder / "transcript.txt"
    if not path.exists():
        return None
    text = path.read_text(encoding="utf-8")
    return None if text.startswith("[Transcript unavailable") else text


def read_info(folder):
    """Extract title and URL from info.md."""
    path = folder / "info.md"
    title, url = folder.name, ""
    if path.exists():
        for line in path.read_text(encoding="utf-8").splitlines():
            if line.startswith("# "):
                title = line[2:].strip()
            if line.startswith("**URL:**"):
                url = line.replace("**URL:**", "").strip()
    return title, url


def load_truth_doc():
    if TRUTH_DOC_PATH.exists():
        return TRUTH_DOC_PATH.read_text(encoding="utf-8")
    return INITIAL_DOC


def save_truth_doc(content):
    TRUTH_DOC_PATH.write_text(content, encoding="utf-8")


def load_progress():
    if PROGRESS_PATH.exists():
        return set(PROGRESS_PATH.read_text(encoding="utf-8").splitlines())
    return set()


def save_progress(done):
    PROGRESS_PATH.write_text("\n".join(sorted(done)), encoding="utf-8")


def call_claude(client, truth_doc, transcript, title, url):
    """Ask Claude what's new in this transcript. Returns additions or NO_NEW_INFO."""
    # Truncate transcript to ~6000 chars to stay within a reasonable token budget
    clipped = transcript[:6000]
    if len(transcript) > 6000:
        clipped += "\n[...transcript clipped for length...]"

    user_msg = f"""\
Current truth document:
---
{truth_doc}
---

New transcript — "{title}"
{url}
---
{clipped}
---

What is NEW in this transcript that is not already covered above?
Add it in the correct section. If nothing is new, reply: NO_NEW_INFO"""

    resp = client.messages.create(
        model=MODEL,
        max_tokens=1500,
        system=SYSTEM,
        messages=[{"role": "user", "content": user_msg}],
    )
    return resp.content[0].text.strip()

# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    api_key = ANTHROPIC_API_KEY or os.environ.get("ANTHROPIC_API_KEY", "")
    if not api_key:
        print("ERROR: Set ANTHROPIC_API_KEY in the script or as an environment variable.")
        return

    client  = anthropic.Anthropic(api_key=api_key)
    folders = get_video_folders()
    if not folders:
        return

    done      = load_progress()
    truth_doc = load_truth_doc()
    pending   = [f for f in folders if f.name not in done]

    print("=" * 60)
    print("  Truth Builder")
    print("=" * 60)
    print(f"  Videos pending : {len(pending)}")
    print(f"  Already done   : {len(done)}")
    print(f"  Truth doc      : {TRUTH_DOC_PATH}")
    print("=" * 60)

    for i, folder in enumerate(pending, 1):
        title, url = read_info(folder)
        transcript = read_transcript(folder)

        if not transcript:
            print(f"\n[{i:02d}/{len(pending)}] SKIP (no transcript) — {title}")
            done.add(folder.name)
            save_progress(done)
            continue

        print(f"\n[{i:02d}/{len(pending)}] {title}")
        print(f"  Asking Claude...", end=" ", flush=True)

        try:
            result = call_claude(client, truth_doc, transcript, title, url)
        except Exception as exc:
            print(f"ERROR: {exc}")
            print("  Skipping and continuing...")
            done.add(folder.name)
            save_progress(done)
            time.sleep(5)
            continue

        if result.strip() == "NO_NEW_INFO":
            print("nothing new.")
        else:
            char_count = len(result)
            print(f"added {char_count} chars.")
            truth_doc += f"\n\n<!-- src: {title} -->\n{result}"
            save_truth_doc(truth_doc)

        done.add(folder.name)
        save_progress(done)
        time.sleep(0.5)  # small pause between API calls

    save_truth_doc(truth_doc)

    print("\n" + "=" * 60)
    print(f"  Done.")
    print(f"  Truth document saved: {TRUTH_DOC_PATH.resolve()}")
    print("=" * 60)


if __name__ == "__main__":
    main()
